### PR TITLE
Fix linter + node-fetch upgrade + minor changes

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
The linter no longer functioned properly. Since 'eslint-config-recommended' is outdated, I hereby suggest a change to 'eslint-config-airbnb'.

### CODE REVIEW

**Comment by fewieden** [comment]
@KristjanESPERANTO thanks for your contribution, I tried to extract all your changes to comment on them.

| Change | Comment |
| --- | --- |
| lint:fix script | good |
| MagicMirror² spelling | good |
| ESLint version | The max version of ESLint should be v7. [Code Climate](https://docs.codeclimate.com/docs/eslint#eslint-versions) doesn't support v8 yet. You also would need to modify the file `.codeclimate.yml`  |
| ESLint config | In the early days of my modules I used `airbnb` code style and other rules. But over the time I found more and more rules that I didn't like. Therefore I switched to `eslint-config-recommended` which was pretty close to the code style I was looking for. Since the package wasn't updated in 2 years I might have to look for an alternative or apply my own rules. |
| node-fetch version | I don't think it is required to update to the esm version of the package, see [discussion](https://github.com/MichMich/MagicMirror/issues/2649). The module works for me also without clicking the TOS agreement. The problem is more related to it being not an official API (some magic to prevent misuse) and it should only be used by their website. As soon as I have an operating [alternative](https://forum.magicmirror.builders/post/99355) I will switch out the source. |

**Comment by KristjanESPERANTO** [comment]
Thanks for the feedback! :slightly_smiling_face: I'll take a closer look, make a few changes and respond to your points.

Next time I'll try to split it into several PRs.

**Comment by KristjanESPERANTO** [comment]
**ESLint version**: I changed it to version 7.x and modified `.codeclimate.yml`.

**node-fetch version:** I changed it to version 2.x. At the moment it also works for me with it :slightly_smiling_face: 

**ESLint config:** I have tried all the style guides that are offered with `npm init @eslint/config`. I chose `airbnb` by exclusion, all the others had something that bothered me 😅 I'm not too attached to `airbnb`, but as long as we haven't found a better alternative, I think it's a step forward compared to `eslint-config-recommended`. Of course we could also deactivate the airbnb rules you don't like. What do you think?

**Comment by fewieden** [comment]
@KristjanESPERANTO regarding the ESLint config I tried to use the same config for all my modules to share the same code style, except the ones I didn't modify in a very long time. I think I have to play with this on my own for a while and apply the code style of my liking to all my modules.

I also found another unofficial data source, so you have a bunch of conflicts.

**Pull request merged**
