### PR TITLE
French translations

### PR DESCRIPTION
**Pull request by fewieden**

### CODE REVIEW

**Comment by fewieden** [comment]
@SirWD thank you for your contribution. I opened your pull request again and pointed it to the correct branch.

Before I can merge you have to make the following two changes:
- Add an entry in the changelog file
- You created a new translation file, but you also have to register the file here https://github.com/fewieden/MMM-OlympicGames/blob/master/MMM-OlympicGames.js#L21

Please let me know if you need help with this

**Comment by SirWD** [comment]
Fixed what was requested. Hope all is well. I apologize I'm a gitHub
contributor newb.

Regards

Le ven. 11 févr. 2022, à 02 h 41, fewieden ***@***.***> a
écrit :

**Comment by fewieden** [comment]
@SirWD I tried to resolve the merge conflicts for you, but I got permission denied. I assume you have to enable edit permission for me.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by fewieden** [comment]
Now that I think about it. I created the pull request for you again so you most likely can't set that. I suggest we close this pull request and you open a new one, so I can help with the conflicts.

**Pull request closed without merging**
