### PR TITLE
Add an option to select specific countries only

### PR DESCRIPTION
**Pull request by mumblebaj**
Hi,

I added an option for a user to provide a list of countries to display instead of a full list. Will display on the countries in `countryList` config option or display the default full list.

Had a bit of an issue fixing Lint issues but seem to have been able to resolve them all now. 

Here is a screen dump of a specific list of countries:

image

Or the default without countryList in config

image

### CODE REVIEW

**Comment by fewieden** [comment]
@mumblebaj you don't have to create a new pull request for every change you do. You can just push new commits to your branch and the open pull request will be updated.

You opened the pull request towards master instead of develop. I changed this now, but you have merge conflicts.

Please let me know if you need my help addressing the other comments that I had in the previous PR.

**Comment by fewieden** [comment]
I handled the remaining comments

**Comment by mumblebaj** [comment]
My apologies. Have been busy with work this week. Had a major release this morning. Thanks for making the changes and again my apologies for only coming back now. But I am off to bed now. Was a long night/morning

**Comment by fewieden** [comment]
@mumblebaj no worries, thanks for your contribution

**Pull request merged**
